# Generated by Django 5.2.1 on 2025-07-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='user',
            name='travel_history',
        ),
        migrations.AddField(
            model_name='user',
            name='budget_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_season',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='travel_style',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
