# Generated by Django 5.2.1 on 2025-07-22 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_preferences_remove_user_travel_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferred_season',
        ),
    ]
