# Generated by Django 5.2.1 on 2025-07-22 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_preferred_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='budget_range',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_destination',
        ),
        migrations.RemoveField(
            model_name='user',
            name='travel_style',
        ),
    ]
