# Generated by Django 5.2.1 on 2025-07-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
