# Generated by Django 5.2.1 on 2025-07-17 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_latitude_blog_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='longitude',
        ),
    ]
