# Generated by Django 5.2.1 on 2025-07-25 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blog_slug'),
        ('destinations', '0021_country_code_country_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='destinations.country'),
        ),
    ]
