# Generated by Django 5.2.1 on 2025-07-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='add_nights',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='add_transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='donation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='flight_help',
            field=models.BooleanField(default=False),
        ),
    ]
