# Generated by Django 5.2.1 on 2025-07-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_booking_add_nights_booking_add_transfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
