# Generated by Django 5.2.1 on 2025-07-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_booking_latitude_alter_booking_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
