# Generated by Django 5.2.1 on 2025-07-23 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_booking_location_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='location_updated_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='longitude',
        ),
        migrations.CreateModel(
            name='BookingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='payments.booking')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
