# Generated by Django 5.2.1 on 2025-07-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_dealcategory_traveltype_dealoffer_traveloption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='countries/'),
        ),
        migrations.AlterField(
            model_name='traveldeal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='deals/'),
        ),
    ]
