# Generated by Django 5.2.1 on 2025-07-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_alter_article_image_alter_country_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldeal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
