# Generated by Django 5.2.1 on 2025-07-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_traveldeal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldeal',
            name='last_minute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='traveldeal',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
