# Generated by Django 5.2.1 on 2025-07-13 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_traveldeal_last_minute_traveldeal_on_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryLearnMoreTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='learn_more_images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learn_more_topics', to='destinations.country')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CountryOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.CharField(max_length=100)),
                ('population', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=100)),
                ('timezone', models.CharField(max_length=50)),
                ('calling_code', models.CharField(max_length=20)),
                ('electricity', models.TextField()),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overview', to='destinations.country')),
            ],
        ),
    ]
