# Generated by Django 5.2.1 on 2025-07-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_countrylearnmoretopic_countryoverview'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldeal',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
