# Generated by Django 5.2.1 on 2025-07-15 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0007_traveldeal_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='country',
        ),
        migrations.AddField(
            model_name='review',
            name='travel_deal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='destinations.traveldeal'),
            preserve_default=False,
        ),
    ]
