# Generated by Django 5.2.1 on 2025-07-15 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0008_remove_review_country_review_travel_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveldeal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='deals/cover/'),
        ),
        migrations.CreateModel(
            name='TravelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='deals/gallery/')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='destinations.traveldeal')),
            ],
        ),
    ]
