# Generated by Django 5.2.1 on 2025-07-15 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0009_alter_traveldeal_image_travelimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelDealDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('language', models.CharField(max_length=100)),
                ('guaranteed', models.BooleanField(default=False)),
                ('rooms', models.CharField(max_length=100)),
                ('original_price', models.CharField(blank=True, max_length=50, null=True)),
                ('discounted_price', models.CharField(max_length=50)),
                ('discount_percent', models.CharField(blank=True, max_length=10, null=True)),
                ('travel_deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='destinations.traveldeal')),
            ],
        ),
    ]
