# Generated by Django 5.2.1 on 2025-07-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0011_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldeal',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='traveldeal',
            name='map_zoom',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
