# Generated by Django 5.2.1 on 2025-07-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0012_traveldeal_city_traveldeal_map_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_inspirational',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='is_suggested',
            field=models.BooleanField(default=False),
        ),
    ]
