# Generated by Django 5.2.1 on 2025-07-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0013_article_is_inspirational_article_is_suggested'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='places/')),
            ],
        ),
        migrations.AddField(
            model_name='traveldeal',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='deals', to='destinations.place'),
        ),
    ]
