# Generated by Django 5.2.1 on 2025-07-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0014_place_traveldeal_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveldeal',
            name='slug',
            field=models.SlugField(blank=True, default=1, unique=True),
            preserve_default=False,
        ),
    ]
