# Generated by Django 5.2.1 on 2025-07-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0015_alter_traveldeal_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldeal',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
