# Generated by Django 5.2.1 on 2025-07-17 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0016_traveldeal_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('accommodation', models.CharField(blank=True, max_length=200)),
                ('activities', models.JSONField(blank=True, default=list)),
                ('meals', models.JSONField(blank=True, default=list)),
                ('travel_deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='destinations.traveldeal')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
    ]
