# Generated by Django 5.2.1 on 2025-07-17 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0017_itineraryday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itineraryday',
            options={'ordering': ['day_number']},
        ),
        migrations.RenameField(
            model_name='itineraryday',
            old_name='day',
            new_name='day_number',
        ),
    ]
