# Generated by Django 5.2.1 on 2025-07-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0018_alter_itineraryday_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldeal',
            name='included_json',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='traveldeal',
            name='not_included_json',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
