# Generated by Django 5.2.1 on 2025-07-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0019_traveldeal_included_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldealdate',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of people allowed for this date'),
        ),
    ]
