# Generated by Django 5.2.1 on 2025-07-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0020_traveldealdate_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='currency_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
