# Generated by Django 5.2.1 on 2025-07-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0021_country_code_country_currency_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='video_url',
        ),
        migrations.AddField(
            model_name='country',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
