# Generated by Django 5.2.1 on 2025-07-25 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0022_remove_country_video_url_country_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealcategory',
            name='discount_percent',
            field=models.CharField(blank=True, help_text="e.g. '15%' for category discount", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='traveldeal',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='destinations.dealcategory'),
        ),
        migrations.AddField(
            model_name='traveldeal',
            name='discount_percent',
            field=models.CharField(blank=True, help_text="e.g. '10%' for deal-wide discount", max_length=10, null=True),
        ),
    ]
